spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

### H2 Console 설정 (test 프로파일에서만 활성화)
#h2:
#  console:
#    enabled: true
#    path: /h2-console


